name: example

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        ci_node_index: [0, 1]
    name: test (${{ matrix.ci_node_index }})

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Run tests
        env:
          KNAPSACK_PRO_COVERAGE_DIRECTORY: "coverage"
          KNAPSACK_PRO_TEST_FILE_PATTERN: "src/**/*.spec.ts"
          KNAPSACK_PRO_TEST_SUITE_TOKEN: ${{ secrets.KNAPSACK_PRO_TEST_SUITE_TOKEN }}
          KNAPSACK_PRO_CI_NODE_TOTAL: 2
          KNAPSACK_PRO_CI_NODE_INDEX: ${{ matrix.ci_node_index }}
          KNAPSACK_PRO_LOG_LEVEL: "error"
        run: |
          cd packages/knapsack-vitest
          npm install
          npm run build
          cd ../example
          npm install
          node ../knapsack-vitest/lib/knapsack-pro-vitest.js --coverage

